[package]
name = "unichain"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
idgenerator = "2.0.0"
serde = { version = "1.0.214", features = ["derive"] }
bincode = "1.3.3"
